name: Check all Terraform

on:
  workflow_call:

jobs:
  terraform-fmt:
    uses: ./.github/workflows/terraform-fmt.yml
  terraform-docs:
    uses: ./.github/workflows/terraform-docs.yml
  checkov:
    uses: ./.github/workflows/checkov.yml
  terraform-tflint:
    uses: ./.github/workflows/terraform-tflint.yml
