name: Terraform-fmt
on:
  workflow_call:

jobs:
  terraform-fmt:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install Terraform
        run: |
          curl -Lo ./terraform.zip https://releases.hashicorp.com/terraform/1.9.5/terraform_1.9.5_linux_amd64.zip
          if [ "$(sha256sum terraform.zip)" != "9cf727b4d6bd2d4d2908f08bd282f9e4809d6c3071c3b8ebe53558bee6dc913b  terraform.zip" ]; then echo "Failed to download terraform due to a checksum mismatch"; exit 1; fi

          mkdir -p "$HOME/.local/bin"
          unzip -d "$HOME/.local/bin" terraform.zip
          rm terraform.zip
          chmod +x "$HOME/.local/bin/terraform"

          echo "$HOME/.local/bin" >> $GITHUB_PATH
      - name: Check terraform formatting
        run: terraform fmt -recursive -diff -check terraform/
